repos:
  - repo: https://github.com/timothycrosley/isort
    rev: stable
    hooks:
      - id: isort
        language_version: python3.7
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.7
