repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.7.0
    hooks:
      - id: isort
        language_version: python3.7
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.7
  - repo: local
    hooks:
    - id: prettier
      name: prettier
      language: system
      types_or: [javascript,jsx,ts,tsx,markdown,html,scss,css,yaml]
      files: ^src/ts/src
      entry: npx prettier --write

