name: Patch test
# ensure src/backend/aspen/workflows/nextstrain_run/combine-and-dedup-fastas.py.patch can be applied cleanly.

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # "At 07:00 UTC on every day-of-week."
    - cron:  '0 7 * * *'

  push:
    branches:
      - trunk
  pull_request:
    branches: "**"

jobs:
  patch:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Check out ncov repo.
        run: |
          mkdir ncov
          cd ncov
          git init
          git fetch --depth 1 git://github.com/nextstrain/ncov.git
          git checkout FETCH_HEAD
      - name: patch
        run: |
          cp src/backend/aspen/workflows/nextstrain_run/combine-and-dedup-fastas.py.patch ncov
          cd ncov
          patch -p1 < combine-and-dedup-fastas.py.patch
