# This workflow will install Python dependencies and run tests with a single version of Python

name: py-tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

# Because of https://github.com/actions/runner/issues/353, we need to explicitly set the shell to bash to get sane defaults (-o pipefail).
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses actions/checkout@v2
      - name: run docker-compose stack
        run: make local-init

  py-code-style:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: py-tests-code-style-v1-${{ runner.os }}-${{ steps.setup.outputs.python-version }}-${{ hashFiles('.github/workflows/py-tests.yml') }}
      - name: Verify code style
        run: make local-style


  py-tests:
    runs-on: ubuntu-latest
    needs: py-code-style

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: py-tests-tests-v1-${{ runner.os }}-${{ steps.setup.outputs.python-version }}-${{ hashFiles('src/py/setup.py', 'src/py/requirements-dev.txt', '.github/workflows/py-tests.yml') }}
      - name: Run with pytest
        run: |
          make local-pytest
